[build-system]
requires = ["hatchling>=1.27.0", "hatch-vcs>=0.4.0"]
build-backend = "hatchling.build"

[project]
name = "asn1ate"
version = "0.6.2"
license = "BSD-3-Clause"
license-files = ["LICENSE.txt"]
description = "ASN.1 translation library."
readme = "README.rst"
authors = [
  { name = "Schneider Electric", email = "OSPO@se.com" },
  { name = "Kim Gräsman", email = "kim.grasman@gmail.com" }
]

classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Topic :: Software Development :: Code Generators"
]

requires-python = ">=3.10"
dependencies = [
  "pyparsing >=2.0.0, !=3.0.5, !=3.0.6",
]

[dependency-groups]
dev = [
  "pyasn1",
  "build"
]

[project.urls]
Repository = "https://github.com/schneider-electric/asn1ate"

[project.scripts]
asn1ate = "asn1ate.pyasn1gen:main_cli"

[tool.hatch.build.targets.wheel]
exclude = ["src/asn1ate/test.py"]
